esphome:
  name: cozytime-bridge
  includes:
    - cozytime_parser.h

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: WARN
  logs:
    cozytime: WARN
    esp32_ble_tracker: WARN

# Enable Home Assistant API (УЖЕ БЕЗ password)
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: "REDACTED_OTA_PASSWORD"

wifi:
  ssid: "REDACTED_WIFI_SSID"
  password: "REDACTED_WIFI_PASSWORD"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Cozytime Bridge Fallback Hotspot"
    password: "REDACTED_AP_PASSWORD"

globals:
  - id: cozytime_temp
    type: float
    initial_value: "0.0"
  - id: cozytime_temp_raw
    type: uint16_t
    initial_value: "0"
  - id: cozytime_humid
    type: float
    initial_value: "0.0"
  - id: cozytime_rssi_value
    type: int8_t
    initial_value: "0"
  - id: cozytime_battery
    type: int
    initial_value: "0"
  - id: cozytime_raw_packet
    type: std::string
    initial_value: '""'

# ============================================
# BLE СКАНЕР
# ============================================
esp32_ble_tracker:
  scan_parameters:
    interval: 5s       # Сканировать каждые 5 секунд
    window: 1.1s       # Длительность окна сканирования
    active: true
  on_ble_advertise:
    - lambda: |-
        // Парсер CozyTime
        // Проверяем manufacturer data с UUID 0x51C9 (CozyTime)

        for (auto &mfg_data : x.get_manufacturer_datas()) {
          // ВАЖНО: Сначала проверяем manufacturer UUID
          if (mfg_data.uuid.get_uuid().len != ESP_UUID_LEN_16) {
            continue;
          }

          uint16_t uuid = mfg_data.uuid.get_uuid().uuid.uuid16;
          if (uuid != 0x51C9) {
            continue;  // Не CozyTime, пропускаем
          }

          const auto& data = mfg_data.data;

          // Проверяем минимальный размер
          if (data.size() < 14) {
            ESP_LOGW("cozytime", "CozyTime packet too short: %d bytes", data.size());
            continue;
          }

          // Проверяем фиксированный префикс CECD6CCE (первые 4 байта)
          if (data[0] == 0xCE && data[1] == 0xCD && data[2] == 0x6C && data[3] == 0xCE) {
            // Нашли CozyTime!

            // Формируем hex строку всех байтов пакета для логирования
            char hex_str[60];
            snprintf(hex_str, sizeof(hex_str),
                     "%02X %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X",
                     data[0], data[1], data[2], data[3], data[4], data[5], data[6],
                     data[7], data[8], data[9], data[10], data[11], data[12], data[13]);
            id(cozytime_raw_packet) = hex_str;

            // Собираем 16-битное значение температуры из байтов 5 и 6
            // Big-endian: byte[6] старший, byte[5] младший
            uint16_t temp_value = (data[6] << 8) | data[5];

            uint8_t humid_byte = data[7];    // byte[7] для влажности (прямое значение)
            uint8_t battery_byte = data[8];  // byte[8] для заряда батареи (прямое значение)

            // Вычисляем температуру по откалиброванной формуле
            // Формула получена методом линейной регрессии по 18 точкам (-40 до 91.2°F)
            // Точность: RMS = 0.064°F, макс ошибка 0.15°F, R² = 0.999995
            // T(°F) = 0.179987 × temp_value - 40.02
            float temperature = 0.179987 * temp_value - 40.02;
            float humidity = humid_byte;     // Прямое значение byte[7]
            int battery = battery_byte;      // Прямое значение byte[8]

            id(cozytime_temp) = temperature;
            id(cozytime_temp_raw) = temp_value;
            id(cozytime_humid) = humidity;
            id(cozytime_battery) = battery;
            id(cozytime_rssi_value) = x.get_rssi();

            return;
          }
        }

sensor:
  # Температура
  - platform: template
    id: cozytime_temperature
    name: "CozyTime Temperature"
    unit_of_measurement: "°F"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    update_interval: 5s
    lambda: |-
      return id(cozytime_temp);

  # Влажность
  - platform: template
    id: cozytime_humidity
    name: "CozyTime Humidity"
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement
    accuracy_decimals: 0
    update_interval: 5s
    lambda: |-
      return id(cozytime_humid);

  # RSSI (уровень сигнала)
  - platform: template
    id: cozytime_rssi
    name: "CozyTime RSSI"
    unit_of_measurement: "dBm"
    icon: "mdi:wifi"
    accuracy_decimals: 0
    update_interval: 5s
    lambda: |-
      return id(cozytime_rssi_value);

  # Заряд батареи
  - platform: template
    id: cozytime_battery_level
    name: "CozyTime Battery"
    unit_of_measurement: "%"
    device_class: battery
    accuracy_decimals: 0
    update_interval: 5s
    lambda: |-
      return id(cozytime_battery);

  # Сырое значение температуры (16-bit temp_value)
  - platform: template
    id: cozytime_temperature_raw
    name: "CozyTime Temperature RAW"
    accuracy_decimals: 0
    update_interval: 5s
    lambda: |-
      return id(cozytime_temp_raw);

  - platform: template
    name: "CozyTime Test Counter"
    id: cozytime_test_counter
    unit_of_measurement: "cnt"
    update_interval: 5s
    lambda: |-
      static int value = 0;
      value += 1;
      return value;

binary_sensor:
  - platform: status
    name: "CozyTime Bridge Status"
    id: cozytime_status

text_sensor:
  - platform: template
    id: cozytime_raw_packet_sensor
    name: "CozyTime RAW Packet"
    icon: "mdi:code-brackets"
    update_interval: 5s
    lambda: |-
      return id(cozytime_raw_packet);

captive_portal:
